### ISSUE TITLE
Missing screenshots

### ISSUE THREAD

**Issue by danrabbit** [georgekap1an/chores#4]
You'll need to provide a screenshot of your app and reference it in your appdata.xml. See the appstream specification and the `⁠<screenshots/>` tag for more info: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by georgekap1an** [comment]
Thanks for the feedback;  I updated the appdata.xml.  Do I need to create a new GitHub release with these changes?
